version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: scholarkit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scholarkit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: scholarkit_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@scholarkit.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data: